services:
  icat_mariadb:
    restart: always
    image: mariadb
    container_name: db_mariadb_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pw
      MARIADB_DATABASE: authn_apikey
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
    # put some test data in the db
    volumes:
      - ./src/test/db_config/import.sql:/docker-entrypoint-initdb.d/init.sql